- name: Create Jenkins Jobs
  hosts: all
  tasks:
    - name: Create Jenkins Jobs
      community.general.jenkins_job:
        config: "{{ lookup('file', 'test.xml') }}"
        name: test
        password: admin
        url: http://172.31.33.79:8080
        user: admin123